#Data Science

Set of methods and practices that make working with data possible

"The way companies generate knowledge for their business, doing science from data. Hence its close relationship with statistics, an area of knowledge whose methods allow describing, exploring, inferring and predicting from data"

https://statplace.com.br/blog/o-que-e-data-science/
https://www.ibm.com/topics/data-science

##Obtaining / Collecting Data

Process to capture information generated by people (or by processes) and that will serve as inputs to plan strategies for the business

It must be done recurrently and consistently by the companies, if possible, be part of the routine

https://mindminers.com/blog/coleta-de-dados-como-fazer/
https://www.simplilearn.com/what-is-data-collection-article 

The first step of every statistical analysis you perform is to determine whether the data you are dealing with is a population or a sample.

- Population: is a collection of all items of interest to our study. The numbers we have obtained when using a population are called parameters.

- Sample: is a subset of the population. The numbers we obtain when working with a sampleare called statistics.

Populations are hard to define and hard to observe and hard to contact in real life. 

A sample, however, is much easier to gather. It is less time consuming and less costly (cheaper).

Time and resources are the main reasons we prefer drawing samples, compared to analysing an entire population.

That's why statistical tests are designed to work with incomplete data.

You will almost always be working with sample data and make data driven decisions and inferences based on it.

Since statistical tests are usually based on sample data, samples are key to accurate statistical insights.

They have two defining caracteristics randomness and representativiness.

A sample must be both random and representative for an insight, to be precise.

- Randomness: A random sample is collected when each member of the sample is chosen from the population, strictly by chance.
- Representativiness: A representative sample is a subset of the population that accurately reflects the members of the entire population.

###Python libraries

- **Scrapy**: used to create bots that scan web pages and collect structured data. Can extract data from API

- **Beautiful soup**: Python data mining and extraction library that extracts data from HTML and XML source

- **Pandas**: provides high-level data structures and a wide range of tools for analysis.

https://www.w3schools.com/python/pandas/pandas_intro.asp

##Preprocessing

Set of activities that involve converting raw data into prepared data, that is, into useful and efficient formats. It is a process that comprises the preparation, organization and structuring of data.

It is an essential phase that carries out analysis and modeling. In addition, it is a step for us to choose which data makes sense to be part of our dataset.

https://medium.com/data-hackers/pr%C3%A9-processamento-de-dados-com-python-53b95bcf5ff4
https://learnpython.com/blog/data-processing-in-python/
https://www.edlitera.com/en/blog/posts/python-data-processing

- **Pandas**

- **Seaborn**

- **Scikit-Learn**: includes functionality for handling datasets and processing metrics

##Analysis and molding

Transform and organize data to make future predictions, to make data-driven decisions.

Model the data to represent information

- **NumPy**: "Numerical Python". Most applications in Analysis and Data Science are based on NumPy or on libraries built from it.

- **Pandas**: Designed to make working with structured data easier

- **SciPy**: Scientific computing library based on NumPy

- **StatsModels**: Provides classes and functions for use in statistical models

https://www.w3schools.com/python/numpy/numpy_intro.asp

##Evaluation and presentation

- **Matplotlib**: Generates two-dimensional graphs, from histograms to heat graphs. It's behind the graphics given by pandas.

- **Seaborn**: Works on top of matplotlib improving the appearance of the graphs, making them more pleasant

- **Pyplot**: Capable of creating high quality interactive graphics

#Numpy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great StackOverflow post.
http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists


```
conda install numpy
```

or

```
pip install numpy
```

**Only on computer**

##Using numpy

Once you've installed NumPy you can import it as a library:

**Colab environment comes with a number of pre-installed scientific and machine learning packages such as numpy, scipy, pandas, tensorflow, and pytorch.**

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We will see some of the most important aspects of Numpy: vectors, arrays, matrices, and number generation. Let's start by discussing arrays.

##Numpy arrays

NumPy arrays are the main way we will use Numpy. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimension arrays and matrices are 2-dimensions (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###Built-in Methods

arrange

Return evenly spaced values within a given interval.

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

zeros and ones

Generate arrays of zeros or ones

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

inspace
Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

###eye

Creates an identity matrix

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###Random

Numpy also has lots of ways to create random number arrays:

rand

Create an array of the given shape and populate it with
random samples from a uniform distribution
over `[0, 1)`.

In [ ]:
np.random.rand(2)

array([0.52848762, 0.74019679])

In [ ]:
np.random.rand(5,5)

array([[0.37216275, 0.39426016, 0.13384727, 0.10517329, 0.48072828],
       [0.97064019, 0.11796114, 0.89148359, 0.54506668, 0.50983624],
       [0.80930578, 0.33454268, 0.71292   , 0.68222958, 0.86729655],
       [0.49370415, 0.62590562, 0.76985754, 0.34203156, 0.61856727],
       [0.80748443, 0.50563823, 0.90596005, 0.76664744, 0.86743333]])

randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
np.random.randn(2)

array([0.38550906, 2.09604692])

In [ ]:
np.random.randn(5,5)

array([[-1.03164136, -0.24124844,  0.5627117 ,  1.83433125, -0.97638805],
       [ 0.03748964,  0.87752821,  0.24244493, -0.5638233 , -0.49739619],
       [-0.15141442,  1.29787296,  0.04443045,  0.20754492, -0.37944663],
       [-0.81779815, -0.50666965,  0.55006088, -1.00502175,  0.66965982],
       [-1.34919214,  0.44132644,  0.80111289,  0.01101066, -0.25164561]])

randint

Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(1,100)

59

In [ ]:
np.random.randint(1,100,10)

array([16, 53, 10, 42, 12,  5, 93, 53, 20, 59])

###Array Attributes and Methods

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([45,  6, 47, 22,  1,  8, 27, 25, 35,  3])

###Reshape

Returns an array containing the same data with a new shape.

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

array([45,  6, 47, 22,  1,  8, 27, 25, 35,  3])

In [ ]:
ranarr.max()

47

In [ ]:
ranarr.argmax()

2

In [ ]:
ranarr.min()

1

In [ ]:
ranarr.argmin()

4

###Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr.shape

(25,)

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

dtype

You can also grab the data type of the object in the array:

In [ ]:
arr.dtype

dtype('int64')

##Index and Selection

In [ ]:
#Creating sample array
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###Bracket Indexing and Selection

The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
#Get a value at an index
arr[8]

8

In [ ]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

###Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [ ]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
# Reset array
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Slice
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

###Indexing a 2D array (matrices)

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order

In [ ]:
#Set up matrix
arr2d = np.zeros((10,10))

In [ ]:
#Length of array
arr_length = arr2d.shape[1]

In [ ]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [ ]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

###Selection

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

##Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [ ]:
arr = np.arange(0,10)

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

<ipython-input-66-2f119c028196>:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Also warning, but not an error instead infinity
1/arr

<ipython-input-67-c81c9b6169c9>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

##Universal Array Functions

Numpy comes with many universal array functions http://docs.scipy.org/doc/numpy/reference/ufuncs.html, which are essentially just mathematical operations you can use to perform the operation across the array.

In [ ]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.max(arr) #same as arr.max()

9

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

<ipython-input-73-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

#Pandas

Now we will learn about a pandas datatype, the Series data type. 

A Series is very similar to a NumPy array (in fact it is built on top of the NumPy array object). What differentiates the NumPy array from a Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just a number location. It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

In [ ]:
import numpy as np
import pandas as pd

##Creating a series

You can convert a list,numpy array, or dictionary to a Series:

In [ ]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}

In [ ]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

###Lists

In [ ]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

###NumPy Arrays

In [ ]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

###Dictionary


In [ ]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

##Using an Index

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look ups of information (works like a hash table or dictionary).


In [ ]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])

In [ ]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [ ]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [ ]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [ ]:
ser1['USA']

1

Operations are then also done based off of index:

In [ ]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

##Dataframes

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index.

In [ ]:
from numpy.random import randn
np.random.seed(707)

In [ ]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [ ]:
df

W         X         Y         Z
A -0.449997 -1.338987  0.389883 -1.028258
B -1.230284 -0.568561  0.216784 -0.198784
C  0.300965 -0.245971 -1.842582  1.619634
D -0.748286  1.075219 -1.188091 -1.380288
E  1.221813 -0.842910  0.398684  0.882263

###Selection and Indexing

In [ ]:
df['W']

A   -0.449997
B   -1.230284
C    0.300965
D   -0.748286
E    1.221813
Name: W, dtype: float64

In [ ]:
# Pass a list of column names
df[['W','Z']]

W         Z
A -0.449997 -1.028258
B -1.230284 -0.198784
C  0.300965  1.619634
D -0.748286 -1.380288
E  1.221813  0.882263

In [ ]:
# SQL Syntax (NOT RECOMMENDED!)
df.W

A   -0.449997
B   -1.230284
C    0.300965
D   -0.748286
E    1.221813
Name: W, dtype: float64

DataFrame Columns are just Series

In [ ]:
type(df['W'])

pandas.core.series.Series

**Creating a new column:**

In [ ]:
df['K'] = df['X'] + df['Y']

**Removing columns**

In [ ]:
df.drop('K',axis=1)

W         X         Y         Z
A -0.449997 -1.338987  0.389883 -1.028258
B -1.230284 -0.568561  0.216784 -0.198784
C  0.300965 -0.245971 -1.842582  1.619634
D -0.748286  1.075219 -1.188091 -1.380288
E  1.221813 -0.842910  0.398684  0.882263

In [ ]:
# Not inplace unless specified!
df

W         X         Y         Z         K
A -0.449997 -1.338987  0.389883 -1.028258 -0.949104
B -1.230284 -0.568561  0.216784 -0.198784 -0.351777
C  0.300965 -0.245971 -1.842582  1.619634 -2.088553
D -0.748286  1.075219 -1.188091 -1.380288 -0.112873
E  1.221813 -0.842910  0.398684  0.882263 -0.444226

In [ ]:
df.drop('K',axis=1,inplace=True)

In [ ]:
df

W         X         Y         Z
A -0.449997 -1.338987  0.389883 -1.028258
B -1.230284 -0.568561  0.216784 -0.198784
C  0.300965 -0.245971 -1.842582  1.619634
D -0.748286  1.075219 -1.188091 -1.380288
E  1.221813 -0.842910  0.398684  0.882263

Can also drop rows this way:

In [ ]:
df.drop('E',axis=0)

W         X         Y         Z
A -0.449997 -1.338987  0.389883 -1.028258
B -1.230284 -0.568561  0.216784 -0.198784
C  0.300965 -0.245971 -1.842582  1.619634
D -0.748286  1.075219 -1.188091 -1.380288

Selecting Rows

In [ ]:
df.loc['A']

W   -0.449997
X   -1.338987
Y    0.389883
Z   -1.028258
Name: A, dtype: float64

Or select based off of position instead of label

In [ ]:
df.iloc[2]

W    0.300965
X   -0.245971
Y   -1.842582
Z    1.619634
Name: C, dtype: float64

Selecting subset of rows and columns

In [ ]:
df.loc['B','Y']

0.2167839883246347

In [ ]:
df.loc[['A','B'],['W','Y']]

W         Y
A -0.449997  0.389883
B -1.230284  0.216784

###Conditional Selection

In [ ]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [ ]:
df>0

W      X      Y      Z
A  False   True  False   True
B  False  False   True  False
C   True  False  False  False
D   True  False  False   True
E  False   True   True  False

In [ ]:
df[df>0]

W         X         Y         Z
A       NaN  0.671278       NaN  0.573098
B       NaN       NaN  0.228719       NaN
C  0.842512       NaN       NaN       NaN
D  0.873616       NaN       NaN  1.054280
E       NaN  0.112879  1.422860       NaN

In [ ]:
df[df['W']>0]

W         X         Y        Z
C  0.842512 -0.417945 -0.110381 -1.49914
D  0.873616 -1.322668 -1.107649  1.05428

For two conditions you can use | and & with parenthesis:

In [ ]:
df[(df['W']>0) & (df['Z'] > 1)]

W         X         Y        Z
D  0.873616 -1.322668 -1.107649  1.05428

###More Index Details

In [ ]:
# Reset to default 0,1...n index
df.reset_index()

index         W         X         Y         Z
0     A -0.226482  0.671278 -1.458014  0.573098
1     B -1.223475 -1.694139  0.228719 -0.125433
2     C  0.842512 -0.417945 -0.110381 -1.499140
3     D  0.873616 -1.322668 -1.107649  1.054280
4     E -1.023400  0.112879  1.422860 -0.917819

In [ ]:
newind = 'CA NY WY OR CO'.split()

In [ ]:
df['States'] = newind

In [ ]:
df

W         X         Y         Z States
A -0.226482  0.671278 -1.458014  0.573098     CA
B -1.223475 -1.694139  0.228719 -0.125433     NY
C  0.842512 -0.417945 -0.110381 -1.499140     WY
D  0.873616 -1.322668 -1.107649  1.054280     OR
E -1.023400  0.112879  1.422860 -0.917819     CO

In [ ]:
df.set_index('States')

W         X         Y         Z
States                                        
CA     -0.226482  0.671278 -1.458014  0.573098
NY     -1.223475 -1.694139  0.228719 -0.125433
WY      0.842512 -0.417945 -0.110381 -1.499140
OR      0.873616 -1.322668 -1.107649  1.054280
CO     -1.023400  0.112879  1.422860 -0.917819

In [ ]:
df

W         X         Y         Z States
A -0.226482  0.671278 -1.458014  0.573098     CA
B -1.223475 -1.694139  0.228719 -0.125433     NY
C  0.842512 -0.417945 -0.110381 -1.499140     WY
D  0.873616 -1.322668 -1.107649  1.054280     OR
E -1.023400  0.112879  1.422860 -0.917819     CO

In [ ]:
df.set_index('States',inplace=True)

In [ ]:
df

W         X         Y         Z
States                                        
CA     -0.226482  0.671278 -1.458014  0.573098
NY     -1.223475 -1.694139  0.228719 -0.125433
WY      0.842512 -0.417945 -0.110381 -1.499140
OR      0.873616 -1.322668 -1.107649  1.054280
CO     -1.023400  0.112879  1.422860 -0.917819

###Multi-Index and Index Hierarchy

In [ ]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [ ]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [ ]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1 -1.290804  1.508736
   2 -1.779278 -0.127549
   3 -1.525004  1.141787
G2 1  3.222914 -2.725416
   2  0.560923  0.676572
   3  1.720337 -0.371321

Now let's show how to index this! For index hierarchy we use df.loc[  ], if this was on the columns axis, you would just use normal bracket notation df[  ]. Calling one level of the index returns the sub-dataframe:

In [ ]:
df.loc['G1']

A         B
1 -1.290804  1.508736
2 -1.779278 -0.127549
3 -1.525004  1.141787

In [ ]:
df.loc['G1'].loc[1]

A   -1.290804
B    1.508736
Name: 1, dtype: float64

In [ ]:
df.index.names

FrozenList([None, None])

In [ ]:
df.index.names = ['Group','Num']

In [ ]:
df

A         B
Group Num                    
G1    1   -1.290804  1.508736
      2   -1.779278 -0.127549
      3   -1.525004  1.141787
G2    1    3.222914 -2.725416
      2    0.560923  0.676572
      3    1.720337 -0.371321

In [ ]:
df.xs('G1')

A         B
Num                    
1   -1.290804  1.508736
2   -1.779278 -0.127549
3   -1.525004  1.141787

In [ ]:
df.xs(['G1',1])

<ipython-input-128-c549ee06ce91>:1: FutureWarning: Passing lists as key for xs is deprecated and will be removed in a future version. Pass key as a tuple instead.
  df.xs(['G1',1])


A   -1.290804
B    1.508736
Name: (G1, 1), dtype: float64

In [ ]:
df.xs(1,level='Num')

A         B
Group                    
G1    -1.290804  1.508736
G2     3.222914 -2.725416

##Missing Data

In [ ]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [ ]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [ ]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [ ]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [ ]:
df.fillna(value='FILL VALUE')

A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

##Groupby

The groupby method allows you to group rows of data together and call aggregate functions

In [ ]:
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

Now you can use the .groupby() method to group rows together based off of a column name. For instance let's group based off of Company. This will create a DataFrameGroupBy object:

In [ ]:
df.groupby('Company')

You can save this object as a new variable:

In [ ]:
by_comp = df.groupby("Company")

In [ ]:
by_comp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [ ]:
df.groupby('Company').mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

###More examples of aggregate methods

In [ ]:
by_comp.std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [ ]:
by_comp.min()

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [ ]:
by_comp.max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [ ]:
by_comp.count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [ ]:
by_comp.describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [ ]:
by_comp.describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [ ]:
by_comp.describe().transpose()['GOOG']

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOG, dtype: float64

##Merging, Joining, and Concatenating



There are 3 main ways of combining DataFrames together: Merging, Joining and Concatenating.

###Example DataFrames

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [ ]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [ ]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

###Concatenation

Concatenation basically glues together DataFrames. Keep in mind that dimensions should match along the axis you are concatenating on. You can use pd.concat and pass in a list of DataFrames to concatenate together:

In [ ]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

###Example DataFrames

In [ ]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']}) 

###Merging

The merge function allows you to merge DataFrames together using a similar logic as merging SQL Tables together. For example:

In [ ]:
pd.merge(left,right,how='inner',on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

Or to show a more complicated example:

In [ ]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
pd.merge(left, right, on=['key1', 'key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [ ]:
pd.merge(left, right, how='outer', on=['key1', 'key2'])

key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

In [ ]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [ ]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

###Joining

Joining is a convenient method for combining the columns of two potentially differently-indexed DataFrames into a single result DataFrame.

In [ ]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [ ]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [ ]:
left.join(right, how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

##Operations

In [ ]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

###Info on Unique Values

In [ ]:
df['col2'].unique()

array([444, 555, 666])

In [ ]:
df['col2'].nunique()

3

In [ ]:
df['col2'].value_counts()

###Selecting data

In [ ]:
#Select from DataFrame using criteria from multiple columns
newdf = df[(df['col1']>2) & (df['col2']==444)]

In [ ]:
newdf

col1  col2 col3
3     4   444  xyz

###Applying Functions

In [ ]:
def times2(x):
    return x*2

In [ ]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [ ]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [ ]:
df['col1'].sum()

10

**Permanently Removing a Column**

In [ ]:
del df['col1']

In [ ]:
df

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

**Get column and index names:**

In [ ]:
df.columns

Index(['col2', 'col3'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=4, step=1)

**Sorting and Ordering a DataFrame:**

In [ ]:
df.sort_values(by='col2') #inplace=False by default

col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

**Find Null Values or Check for Null Values**

In [ ]:
df.isnull()

col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

In [ ]:
# Drop rows with NaN Values
df.dropna()

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [ ]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [ ]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [ ]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN